### ISSUE TITLE
'전북' 데이터를 입력 시, 오류가 발생합니다.

### ISSUE THREAD

**Issue by everydayday** [TENQUBE/react-korea-bubble-map#1]
안녕하세요. 좋은 패키지 감사드립니다.

패키지 이용 중,
'전북'에 해당하는 sido의 code 
5200000000 입력 시

> Cannot read properties of undefined (reading 'geometry')

라는 오류가 발생하네요.

다른 지역에 대해선 오류 발생하지 않는데
'전북'지역만 발생해 문의드립니다.

**Comment by wansiklee** [comment]
안녕하세요!

0.0.3 버전에서 사용하는 데이터는 2023년 12월 26일자의 행정구역도 데이터를 사용하고 있습니다.
해당 이슈는 2024년 1월 18일 "전라북도"에서 "전북특별자치도"로 전환되면서 해당 법정동코드가 변경되면서 발생한 문제입니다.

0.0.4 버전에서 2024년 2월 13일 기준 데이터로 업데이트 진행했습니다.
관심 가져주셔서 감사합니다.
